In [18]:
# 행복	중립	슬픔	공포	혐오	분노	놀람 비율 확인필요
# 데이터셋/한국어_연속적_대화_데이터셋.xlsx

In [35]:
import pandas as pd

data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화말뭉치(최종데이터)_Training.xlsx"
df = pd.read_excel(data_url)
df.head(5)

# '''print(df["감정_대분류"].value_counts())
# print("\nunique 값:", df["감정_대분류"].unique())'''

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,일은 왜 해도 해도 끝이 없을까? 화가 난다.,많이 힘드시겠어요. 주위에 의논할 상대가 있나요?,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.,NaN,NaN
1,2,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,월급이 줄어든 만큼 소비를 줄일 계획이군요.,NaN,NaN
2,3,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,스트레스받지 않기 위해선 인간관계에 있어 약간의 거리를 두는 게 좋겠군요.,NaN,NaN
3,4,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,관련 없는 심부름을 모두 하게 되어서 노여우시군요. 어떤 것이 상황을 나아질 수 있...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,직장 사람들과 이야기를 해 보겠다고 결심하셨군요.,NaN,NaN
4,5,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,무시하는 것 같은 태도에 화가 나셨군요. 상대방의 어떤 행동이 그런 감정을 유발하는...,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,항상 먼저 인사하게 되어 화가 나셨군요. 어떻게 하면 신입사원에게 화났음을 표현할 ...,NaN,NaN

In [75]:
import pandas as pd

data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"
df = pd.read_excel(data_url)
df.head(5)

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.
1,2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.
2,3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.
3,4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.
4,5,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.

In [76]:

data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\한국어_연속적_대화_데이터셋.xlsx"
df = pd.read_excel(data_url)
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,행복,중립,슬픔,공포,혐오,분노,놀람
0,dialog #,발화,감정,NaN,NaN,1030.0,NaN,NaN,NaN,NaN,NaN,NaN
1,S,아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!,분노,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.,혐오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,손님 왔어요.,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,손님? 누구?,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
import pandas as pd
import numpy as np

# 데이터 로드
fin_t=pd.read_excel((r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화\Training_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.xlsx"), engine='openpyxl')
fin_v=pd.read_excel((r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"), engine='openpyxl')

# 

# 결측치 처리
fin_t=fin_t.fillna("")
fin_v=fin_v.fillna("")

# 컬럼간 str 합치기
fin_t["사람문장"]=fin_t["사람문장1"].astype(str)+fin_t["사람문장2"].astype(str)+fin_t["사람문장3"].astype(str)
fin_v["사람문장"]=fin_v["사람문장1"].astype(str)+fin_v["사람문장2"].astype(str)+fin_v["사람문장3"].astype(str)

# 데이터프레임 합치기
df_concat=pd.concat([fin_t,fin_v])
final_df=df_concat[["사람문장","감정_대분류"]]
final_df=final_df.rename({"감정_대분류":"감정"},axis=1)

#컬럼 내 데이터들의 공백(string) 제거
final_df["감정"]=final_df["감정"].apply(lambda x:x.strip())
final_df["감정"].value_counts()

final_df.head()

                                                사람문장  감정
0  일은 왜 해도 해도 끝이 없을까? 화가 난다.그냥 내가 해결하는 게 나아. 남들한테...  분노
1  이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나....  분노
2  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...  분노
3  직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...  분노
4  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.상사인 나에게 먼...  분노

In [62]:

# 감정 컬럼에서 "상처"로 시작하는 문자열을 "슬픔"으로, "기쁨"으로 시작하는 문자열을 "행복"으로 변경
final_df["감정"]=np.where(final_df["감정"].str.match("상처"),"슬픔",final_df["감정"])
final_df["감정"]=np.where(final_df["감정"].str.match("기쁨"),"행복",final_df["감정"])
final_df=final_df.reset_index(drop=True)

# 컬럼명 변경
final_df.rename({"사람문장":"발화"},axis=1,inplace=True)

In [67]:
# 연속적 대화 데이터셋 로드
con_dialogue=pd.read_excel(r'C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\한국어_연속적_대화_데이터셋.xlsx')
con_dialogue.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,행복,중립,슬픔,공포,혐오,분노,놀람
0,dialog #,발화,감정,NaN,NaN,1030.0,NaN,NaN,NaN,NaN,NaN,NaN
1,S,아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!,분노,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.,혐오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,손님 왔어요.,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,손님? 누구?,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
# 첫행을 컬럼으로 바꾸기
new_columns=con_dialogue.iloc[0]
con_dialogue=con_dialogue.rename(columns=new_columns).iloc[:,1:3]
con_dialogue.drop(index=0,axis=0,inplace=True)
con_dialogue.head()

                                             발화  감정
1          아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!  분노
2  그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.  혐오
3                                       손님 왔어요.  중립
4                                       손님? 누구?  중립
5                                몰라요. 팀장님 친구래요.  중립

In [70]:
con_dialogue["감정"].value_counts()

# 오타 수정하기
# 분ㄴ -> 분노
# 분 -> 분노
# ㅈ중립 -> 중립
# 중림 -> 중립
# ㄴ중립 -> 중립
# 줄 -> 중립
# 'ㅍ' -> ????

correction_dict = {
    '분ㄴ': '분노',
    '분': '분노',
    '중림': '중립',
    'ㅈ중립': '중립',
    'ㄴ중립': '중립',
    '줄': '중립'
}

con_dialogue['감정'] = con_dialogue['감정'].replace(correction_dict)

#%%
con_dialogue["감정"].value_counts()

감정
중립    43790
놀람     4866
분노     3633
슬픔     1972
행복     1030
혐오      220
공포       98
ㅍ        12
Name: count, dtype: int64

In [71]:
con_dialogue=con_dialogue[con_dialogue["감정"].isin(["중립","놀람","분노","슬픔","행복","혐오","공포"])]
# 감정 Label 일정하게 맞춰주기 (감성대화 말뭉치와 통합을 위해)

con_dialogue["감정"]=np.where(con_dialogue["감정"].str.match("놀람"),"당황",con_dialogue["감정"])
con_dialogue["감정"]=np.where(con_dialogue["감정"].str.match("공포"),"불안",con_dialogue["감정"])

con_dialogue["감정"].value_counts()

감정
중립    43790
당황     4866
분노     3633
슬픔     1972
행복     1030
혐오      220
불안       98
Name: count, dtype: int64

In [72]:
# 데이터 합치기

real_final_df=pd.concat([final_df,con_dialogue])
real_final_df.reset_index(drop=True,inplace=True)
real_final_df.to_csv("real_final_df.csv",index=False,encoding="utf-8-sig")

In [ ]:
real_final_df["감정"].value_counts()
real_final_df.to_csv("sentiment_dialogues.csv")

In [74]:
real_final_df.head(10)

                                                  발화  감정
0  일은 왜 해도 해도 끝이 없을까? 화가 난다.그냥 내가 해결하는 게 나아. 남들한테...  분노
1  이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나....  분노
2  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...  분노
3  직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...  분노
4  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.상사인 나에게 먼...  분노
5  직장에 다니고 있지만 시간만 버리는 거 같아. 진지하게 진로에 대한 고민이 생겨.직...  분노
6  성인인데도 진로를 아직도 못 정했다고 부모님이 노여워하셔. 나도 섭섭해.부모님께 좀...  분노
7  퇴사한 지 얼마 안 됐지만 천천히 직장을 구해보려고.더 좋은 회사가 기다리고 있을지...  행복
8  졸업반이라서 취업을 생각해야 하는데 지금 너무 느긋해서 이래도 되나 싶어.응. 느긋...  불안
9  요즘 직장생활이 너무 편하고 좋은 것 같아!우리 회사는 복지가 정말 좋아! 내가 곧...  행복

In [42]:
# 사람문장과 시스템문장 분리하기
shuffled_train = fin_t.sample(frac=1).reset_index(drop=True)
shuffled_test = fin_v.sample(frac=1).reset_index(drop=True)


shuffled_train.head()

rows = []

# 각 행에 대해 사람문장과 시스템문장을 분리
for idx, row in shuffled_train.iterrows():
    # 사람문장1에 대한 시스템문장1
    if pd.notna(row['사람문장1']) and pd.notna(row['시스템문장1']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장1'],
            '시스템문장': row['시스템문장1']
        })
    
    # 사람문장2에 대한 시스템문장2
    if pd.notna(row['사람문장2']) and pd.notna(row['시스템문장2']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장2'],
            '시스템문장': row['시스템문장2']
        })

    # 사람문장3에 대한 시스템문장3 (NaN이 아닌 경우에만 추가)
    if pd.notna(row['사람문장3']) and pd.notna(row['시스템문장3']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장3'],
            '시스템문장': row['시스템문장3']
        })

# 새로운 데이터 프레임 생성
train = pd.DataFrame(rows)

train.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장,시스템문장
0,노년,여성,대인관계,만성질환 무,슬픔,비통한,동창회다 친목회다 다 멀리하니 돈은 굳어서 좋지만 사는 재미가 없네. 심심한 건지 ...,건강 때문에 모임을 멀리하신 거예요?
1,노년,여성,대인관계,만성질환 무,슬픔,비통한,건강도 건강이지만 가뜩이나 시원찮은 일감이 갈수록 줄어든 탓이 크지 뭐. 그런데 그...,지금 와서 후회하시는 건가요?
2,노년,여성,대인관계,만성질환 무,슬픔,비통한,기쁘기는커녕 오히려 슬프고 고독한데? 나를 알아주는 사람들이 줄어들었다는 허탈감과 ...,너무 나쁘게만 생각하지 마세요.
3,청년,여성,대인관계,해당없음,당황,외로운,남자친구랑 헤어졌어. 그의 빈자리가 너무 커.,항상 곁에 있던 남자친구가 이제 없네요.
4,청년,여성,대인관계,해당없음,당황,외로운,당장 만나자고 할 만한 친구도 없네.,약속도 잡기가 힘들겠군요.

In [58]:
train['감정_대분류'].value_counts()

감정_대분류
불안    27960
분노    27480
상처    27429
슬픔    27375
당황    26268
기쁨    18378
Name: count, dtype: int64