# 감정 분류 모델1

## 데이터 불러오기 - 감성 대화 말뭉치

In [56]:
# import json

# # 말웅치 json 읽기
# with open('.\데이터셋\감성대화\Training_221115_add\라벨링데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.json', 'r', encoding='utf-8') as f:
#     data = json.load(f)

# # 첫 번째 데이터의 대화 내용 출력 예시
# print(data[0]['talk']['content'])

In [13]:
# data
# # 구조 : [ {'profile' : {딕셔너리 여러개}  , 'id' : {딕셔너리 여러개} } ]

In [57]:
import pandas as pd

# 말뭉치 training 데이터
data_url = ".\데이터셋\감성대화\Training_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.xlsx"
# data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화말뭉치(최종데이터)_Training.xlsx"
df = pd.read_excel(data_url)
df.head(5)

# '''print(df["감정_대분류"].value_counts())
# print("\nunique 값:", df["감정_대분류"].unique())'''

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,일은 왜 해도 해도 끝이 없을까? 화가 난다.,많이 힘드시겠어요. 주위에 의논할 상대가 있나요?,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.,NaN,NaN
1,2,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,월급이 줄어든 만큼 소비를 줄일 계획이군요.,NaN,NaN
2,3,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,스트레스받지 않기 위해선 인간관계에 있어 약간의 거리를 두는 게 좋겠군요.,NaN,NaN
3,4,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,관련 없는 심부름을 모두 하게 되어서 노여우시군요. 어떤 것이 상황을 나아질 수 있...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,직장 사람들과 이야기를 해 보겠다고 결심하셨군요.,NaN,NaN
4,5,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,무시하는 것 같은 태도에 화가 나셨군요. 상대방의 어떤 행동이 그런 감정을 유발하는...,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,항상 먼저 인사하게 되어 화가 나셨군요. 어떻게 하면 신입사원에게 화났음을 표현할 ...,NaN,NaN

In [34]:
import pandas as pd

# 말뭉치 validation 데이터
data_url = ".\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"
# data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"
df = pd.read_excel(data_url)
df.head(5)

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.
1,2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.
2,3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.
3,4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.
4,5,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.

## 데이터 합치기

In [1]:
import pandas as pd
import numpy as np
import re
# 데이터 로드


# 말뭉치 training 데이터
fin_t=pd.read_excel(".\데이터셋\감성대화\Training_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.xlsx", engine='openpyxl')

# 말뭉치 validation 데이터
fin_v=pd.read_excel(".\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx", engine='openpyxl')


# 빈칸은 nan으로 결측치 처리
fin_t=fin_t.fillna("")
fin_v=fin_v.fillna("")

# 사람문장 1,2,3을 한 컬럼으로 합치기
fin_t["사람문장"]=fin_t["사람문장1"].astype(str)+fin_t["사람문장2"].astype(str)+fin_t["사람문장3"].astype(str)
fin_v["사람문장"]=fin_v["사람문장1"].astype(str)+fin_v["사람문장2"].astype(str)+fin_v["사람문장3"].astype(str)

# training과 validation 합치기
df_concat=pd.concat([fin_t,fin_v])
final_df=df_concat[["사람문장","감정_대분류"]]
final_df=final_df.rename({"감정_대분류":"감정"},axis=1)

#컬럼 내 데이터들의 공백(string) 제거
final_df["감정"]=final_df["감정"].apply(lambda x:x.strip())
final_df["감정"].value_counts()


final_df.head()

                                                사람문장  감정
0  일은 왜 해도 해도 끝이 없을까? 화가 난다.그냥 내가 해결하는 게 나아. 남들한테...  분노
1  이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나....  분노
2  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...  분노
3  직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...  분노
4  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.상사인 나에게 먼...  분노

In [2]:
# 감정: 6가지 분류
final_df['감정'].value_counts()

감정
불안    10433
분노    10417
상처    10150
슬픔    10128
당황     9804
기쁨     7339
Name: count, dtype: int64

## 텍스트 정제

In [4]:
# ─────────────────────────────────────────
# 2. 텍스트 정제
# ─────────────────────────────────────────
 
def clean_text(text: str) -> str:
    """특수문자·이모지 제거, 연속 공백 정리"""
    text = re.sub(r'[^\w\s가-힣.,!?]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
 
final_df["사람문장"] = final_df["사람문장"].apply(clean_text)
 
# 텍스트 길이 2자 미만 제거 (합치기 과정에서 생긴 빈 행 처리)
final_df = final_df[final_df["사람문장"].str.len() >= 2].reset_index(drop=True)

## 감정 라벨링

In [5]:
# ─────────────────────────────────────────
# 3. 레이블 인코딩
# ─────────────────────────────────────────
 
EMOTION_MAP = {
    "불안": 0,
    "분노": 1,
    "상처": 2,
    "슬픔": 3,
    "당황": 4,
    "기쁨": 5,
}
 

# 알 수 없는 레이블 확인
unknown = final_df[~final_df["감정"].isin(EMOTION_MAP.keys())]["감정"].unique()
if len(unknown) > 0:
    print(f"⚠ 알 수 없는 레이블 (제거됨): {unknown}")
    final_df = final_df[final_df["감정"].isin(EMOTION_MAP.keys())].reset_index(drop=True)
 
# 6분류 레이블 (0~5)
final_df["label"] = final_df["감정"].map(EMOTION_MAP)
 
# 이진 레이블: 기쁨(5) → 0(긍정), 나머지 → 1(부정)
final_df["is_negative"] = (final_df["label"] != 5).astype(int)

## 중복 제거

In [6]:
# 중복된 행만 추출 (keep=False → 중복 관련 모든 행 표시)
duplicates = final_df[final_df.duplicated(subset=["사람문장"], keep=False)].copy()
duplicates = duplicates.sort_values("사람문장")

print(f"중복 관련 행 수: {len(duplicates)}")
print(f"중복된 고유 텍스트 수: {duplicates['사람문장'].nunique()}")
print()
duplicates.head(20)

중복 관련 행 수: 4
중복된 고유 텍스트 수: 2

,사람문장,감정,label,is_negative
37918,전부 언니는 공부를 잘한다고 언니한테만 잘해주고 나는 무시해.모르겠어. 다들 나만 ...,상처,2,1
37919,전부 언니는 공부를 잘한다고 언니한테만 잘해주고 나는 무시해.모르겠어. 다들 나만 ...,상처,2,1
33804,직장에서 모두들 내 말을 무시하는 거 같아서 슬퍼.응. 내가 딱히 잘못한 것도 없는...,슬픔,3,1
51707,직장에서 모두들 내 말을 무시하는 거 같아서 슬퍼.응. 내가 딱히 잘못한 것도 없는...,슬픔,3,1

In [7]:
# ─────────────────────────────────────────
# 4. 중복 제거
# ─────────────────────────────────────────
 
before = len(final_df)
final_df = final_df.drop_duplicates(subset=["사람문장"]).reset_index(drop=True)
print(f"중복 제거: {before} → {len(final_df)} ({before - len(final_df)}건 제거)")

중복 제거: 58271 → 58269 (2건 제거)

In [8]:
# ─────────────────────────────────────────
# 5. 분포 확인
# ─────────────────────────────────────────
 
print("\n[6분류 감정 분포]")
print(final_df["감정"].value_counts())
 
print("\n[이진 분류 분포 (부정감정 탐지)]")
print(final_df["is_negative"].value_counts().rename({0: "긍정(기쁨)", 1: "부정"}))
 
# 클래스 불균형 경고
counts = final_df["label"].value_counts()
ratio = counts.max() / counts.min()
if ratio > 3:
    print(f"\n⚠ 클래스 불균형 감지 (max/min = {ratio:.1f}x) → class_weight='balanced' 권장")

[6분류 감정 분포]
감정
불안    10433
분노    10417
상처    10149
슬픔    10127
당황     9804
기쁨     7339
Name: count, dtype: int64

[이진 분류 분포 (부정감정 탐지)]
is_negative
부정        50930
긍정(기쁨)     7339
Name: count, dtype: int64

In [ ]:
# # ─────────────────────────────────────────
# # 6. 저장
# # ─────────────────────────────────────────

# # 이미 파일 있으면 오류 발생
# final_df.to_csv("model1_dataset.csv", index=False, encoding="utf-8-sig")
# print(f"\n✅ 저장 완료: model1_dataset.csv ({len(final_df)}행)")
 
# final_df.head()

✅ 저장 완료: model1_dataset.csv (58269행)

                                                사람문장  감정  label  is_negative
0  일은 왜 해도 해도 끝이 없을까? 화가 난다.그냥 내가 해결하는 게 나아. 남들한테...  분노      1            1
1  이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나....  분노      1            1
2  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...  분노      1            1
3  직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...  분노      1            1
4  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.상사인 나에게 먼...  분노      1            1

# 모델링 전처리 단계

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

In [ ]:
# 처음 한번만 실행
# import matplotlib
# matplotlib.use('Agg')

In [26]:
# ─────────────────────────────────────────
# 0. 한글 폰트 설정 (matplotlib)
# ─────────────────────────────────────────
try:
    font_path = fm.findfont(fm.FontProperties(family='Malgun Gothic'))
    plt.rcParams['font.family'] = 'Malgun Gothic'
except:
    plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['axes.unicode_minus'] = False

In [27]:
# ─────────────────────────────────────────
# 1. 이전 전처리 결과 로드
#    (model1_preprocess.py 실행 후 생성된 CSV)
# ─────────────────────────────────────────
final_df = pd.read_csv("model1_dataset.csv", encoding="utf-8-sig")
print(f"로드 완료: {len(final_df)}행\n")

로드 완료: 58269행

## 텍스트 길이 분석

In [28]:
# ─────────────────────────────────────────
# 2. 텍스트 길이 분석 → BERT max_length 결정
# ─────────────────────────────────────────
final_df["text_len"] = final_df["사람문장"].str.len()  # 글자 수 기준
 
desc = final_df["text_len"].describe(percentiles=[.50, .75, .90, .95, .99])
print("[텍스트 길이 분포 (글자 수)]")
print(desc.round(1))
 
# 권장 max_length: 95th percentile 기준으로 설정
p95 = int(desc["95%"])
recommended_max_len = min(p95 + 10, 512)  # BERT 상한 512
print(f"\n→ 권장 max_length: {recommended_max_len} (95th percentile: {p95})")
 
# 길이 분포 시각화
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
 
axes[0].hist(final_df["text_len"], bins=50, color='steelblue', edgecolor='white')
axes[0].axvline(recommended_max_len, color='red', linestyle='--', label=f'max_length={recommended_max_len}')
axes[0].set_title("텍스트 길이 분포")
axes[0].set_xlabel("글자 수")
axes[0].set_ylabel("빈도")
axes[0].legend()

[텍스트 길이 분포 (글자 수)]
count    58269.0
mean        99.1
std         28.4
min         16.0
50%        100.0
75%        117.0
90%        133.0
95%        142.0
99%        169.0
max        306.0
Name: text_len, dtype: float64

→ 권장 max_length: 152 (95th percentile: 142)

In [29]:
# 길이 상위 20개
top_long = final_df.nlargest(20, "text_len")[["사람문장", "감정", "text_len"]]
print(top_long.to_string())

                                                                                                                                                                                                                                                                                                                     사람문장  감정  text_len
38631  아 산다는 것이 무엇인지 조금은 알겠는데 그래도 힘이 드네. 그럭저럭 먹고살 만하게 경제적으로 힘든 것은 없는데 자식 농사를 잘 마감 해야하 는데 소통이 잘 안 되니 말이야.옛말에 부자 삼 대 못 간 다는 말이 있듯이 우리와 나의 부친은 굶으면서 자식들 안 굶기도 학교 마치라고 부유하지는 안 해도 온 정성을 다했는데 얘들은 이걸 모르니.해서 애들을 조금 힘들게 키워야 하는데 외국 유학까지 보내서 공부하도록 했더니 허황된 다른 견들만 갖고서 생활하려 하니 내가 틀리는지 자식들 의견이 다른지 고민이네. 퇴직을 앞두고 이런 고민을 하는 게 불행해.  상처       306
40854  가방끈이 짧다는 말이 무슨 뜻인 줄 알지? 학력이 낮다는 말인데 내가 그래서 친구들은 물론 가족들에게도 무시를 받는 것 같아. 텔레비전에서 나오는 말을 못 알아들을 때도 그렇고 거리에서 간판을 못 읽을 때도 그렇고 수없이 많아. 가족들이 나누는 얘기를 못 알아들을 때 가족들이 나를 바라보는 눈초리는 무시를 넘어서 학대를 하는 느낌이더라고. 게을러서 도중에 포기한 탓에 가방끈이 더 짧아졌지만 주변 사람들하고도 영 안 통하고 외톨이로 지낸다니까. 학교를 그만둔 뒤로 혼자서 한글은 뗐는데 이왕이면 알파벳도 익힐 걸 그랬다는 생각이 뒤늦게 들더라고.  당황       306
40884  남들처럼 배우질 못해서 몸만 믿고 살아왔는데 다리를 다쳤으니 어떡한담. 종일 쉬엄쉬엄 걸어 다녔는데 그걸 못하면 풀칠하기도 힘들 텐데.건강기능식품 같은 걸 파는 외판원을 하고 있는데 나이에 구애도 받지 않고 부지런만 하면 굶어 죽지는 않거든. 얼마 전에는 단골들이랑 산에 올랐다가 미끄러져서 병원을 찾았더니 의사가 앞으로는 한 시간 이상 걷지도 말라잖아.하루 벌어 하루 풀칠하는 형편이니 차가 있을 리도 없지만 차를 누가 주더라도 운전할 줄이나 알겠어? 다리뿐 아니라 귀도 나쁘고 눈도 나쁘고 나쁜 데가 한두 군데가 아니니 죽는 게 나을지도 모르지  분노       306
38503         요즘 들어 외롭다는 생각이 자주 들어. 세상이 변한 건지 내가 변한건지 주변에 있던 말 친구 조차하나둘 떠나 버리고 이 넓은 세상에 나만 혼자 남겨졌다는 생각이 들 때가 있어.말이 통하는 사람이 주변에 없다 보니 나 혼자서 보내는 시간이 많아지고 소외되었다는 생각에 외로움이 더욱 커지는 것을 실감해. 어쩌다 새롭게 알게 된 사람이 생겨도 믿을 수가 없고.그렇긴 하지만 하도 어수선한 세상이라서 좋은 사람인지 나쁜 사람인지 도통 알 수가 없으니 사귀는 게 불안한 건 사실이야. 내가 배운 게 짧아서 대화를 나누기가 자신이 없기도 하고.  상처       299
40889         아무리 바쁜 세상이라고들 하지만 자식들이 돼서 이렇게 무심할 수가 있는 거야? 요즘은 키우는 개도 혼자 오래 내버려 두면 걸린다는데 부모를 방치하는 건 죄가 안 되나 보지?몸이 아픈 어미가 오늘 저녁에 풍이나 치매에 걸릴 줄도 모르는 판인데 더 급한 일이 있겠어? 나이 먹어 보라지 멀쩡한 데가 어디 한 군데라도 남아 있나.이름은 모르겠는데 암튼 척추질환이 있는 데다 산에 나물 뜯으러 갔다가 넘어져서 발까지 삔 뒤론 꼼짝도 못 하겠어. 아파서 아무것도 못 하고 누워 있으려니 자식들한테 더 무시 받는 것 같아 힘들고 두려워서 죽겠어.  당황       299
32298             어제 우리 아들이 무슨 잘못을 해서 야단을 좀 쳤는데 글쎄 걔 말이 엄마가 자기한테 해 준 게 뭐가 있냐고 하는데 기가 막히네. 내가 애들 뒷바라지를 하느라 얼마나 고생을 했는데.아들이 그림을 좀 잘 그리는 편이긴 한데 내가 미대는 절대 안 된다고 하고 그림 도구 같은 걸 다 버렸거든. 근데 부모가 돼서 자식 진로에 대한 결정은 할 수 있지 않겠어?애가 공부할 시간도 없는데 틈만 나면 붓을 잡고 있으니 나도 화가 나서 그랬지. 아들한테 좀 미안한 마음은 있긴 한데 그렇다고 부모한테 그렇게 말을 하는 게 더 나쁜 거 아닌가?  분노       295
40881              변변한 취미도 없고 아픈 데도 많아서 집 근처를 어슬렁거리는 게 유일한 낙인데 그것도 못 하게 됐네. 이러다간 한 걸음도 못 떼어놓는 신세가 될까 봐 걱정이 이만저만이 아니야.집 근처를 왔다 갔다 하는 거야 뭐 마스크를 쓰면 되지만 퇴행성관절염이 심해진 건 수가 없으니. 부모님께 물려받은 위장병에는 걷는 것도 도움이 되고 나도 걷는 걸 좋아하는데. 없는 살림에 해볼 건 다 해본 후 요즘에는 건강기능식품을 열심히 먹고 있어. 다리가 괜찮을 때는 전철로 먼 데까지 가서 국밥도 먹고 왔는데 요즘에는 화장실 가는 것조차 힘들어.  상처       294
38606               내 나이가 예순일곱이야. 내가 이 나이 되면 다른 집에선 부양을 받을 나이인데 나는 지금도 가족 중에서 우리 영감을 부양해야 해서 식당에 일하러 다니고 있어. 외동딸은 외국에서 살지.그래. 나 영감이 중병에 걸려서 간호해야 하고 병원에도 데리고 갔다 와야 하고 일도 하러 다녀야 해. 나도 사실은 신경이 예민해서 쓰러진 적도 있어서 정신과 약을 먹고 있어.우리 집 형편이 이렇게 어려워서 나도 일하러 다녀야 하고 몸이 아픈 영감을 간호해야 하고 나까지도 정신과 치료를 받는 중이어서 나는 무가치한 사람이라는 생각 많이 했어.  분노       293
40877                나이 드니 건강도 나빠지고 수입도 줄어서 사람들을 멀리했더니 모든 게 더 나빠졌네. 몸은 더 약해지고 수입이랑 사람은 끊어졌으니 이걸 어째야 쓸꼬?그게 쉽지 않은 게 사람들을 만나려면 밥값이니 차비니 해서 돈이 만만찮게 들거든. 돈이 없다고 얻어먹으면 오히려 아니 만나느니만 못해서 안 만났더니 사람들을 만나도 화젯거리도 없네. 그런 셈인 게 지금 와서 생각해보니 그나마 주변 사람들 덕에 일거리도 얻고 싱겁게 웃기라도 했는데. 지금은 돈이 한 푼도 없으니 언제 어디서 돈 들어갈 일이 터질까 하고 주위를 두리번거린다니까.  불안       292
38834                    나 처녀 때 직장에 취업해서 열심히 일하고 다녔어. 내 바로 위에 오빠가 있는데 대학에 들어가서 공부를 해서 집안에서 딸인 나는 오빠 대신에 가장 역할을 해야 해서 취직했었어.그때는 오빠만 잘 되면 모든 것이 잘 되고 나도 잘될 거라고 생각해서 그렇게 살아왔어. 그러다 나도 시집가서 자식을 낳아 기르게 되어 직장을 그만두게 되었어.내가 자식을 열심히 기르면 잘 자라서 자식들이 나를 알아줄 줄 알았는데 그렇지가 않아. 나하고 다 따로 살아서 나는 용돈 조금 겨우 받고 지내느라고 내가 하고 싶은 거 할 수가 없어.  불안       288
33380                       친구가 가방을 골라 달라고 하기에 적극적으로 추천해 줬는데 나중에 보니 다른 친구가 추천한 가방을 샀더라고. 이뿐 아니라 친구들이 내 제안을 계속 무시해서 자꾸만 좌절해.어차피 내 의견이 그리 중요하진 않은 것 같아. 나에게 친구들이 의견을 묻는다면 다른 사람들이 어떻게 말했냐고 물어본 후 나도 그렇게 생각한다고 대충 맞장구치고 말 거야.진지하게 의견을 묻는 일이 있다면 성심성의껏 조언을 할 거야. 하지만 일상에서 지나가듯 물어보고 무시하는 행동에 일일이 상처받고 싶지 않아. 그냥 나도 무심히 답할 거야.  분노       285
27655                         아 결국 친구한테 빌려준 돈을 떼이게 생겼어. 급전이 필요하다고 부탁해서 여러차례 빌려준게 벌써 천 만원이 넘는데 십 년이 지나도 갚을 생각을 안하는것 같아 연락을 했더니 전화번호도 바꾸고 잠적해버렸네. 나뿐만 아니고 이 친구한테 당한 사람이 한둘이 아냐. 아주 상습범이더구만.각별히 친했다기 보다는 오래 알고 지내던 사이였는데 평소에 들리는 소문이 좀 좋진 않았어도 설마설마 했는데 아주 사기꾼이었다고 하더라고. 내일 당장 경찰서에 가서 고소할거야.딸이 왜 그런 선택을 하게 되었는지 대화를 나눠봐야겠어.  상처       283
40888                           사람들이 통 안 보이니 인걸은 간데없다는 옛날에 배운 시조까지 갑자기 떠오르네? 다 내 탓이긴 하지만. 내가 좀 예민한 편인 데다 깔끔하기도 하고 그 위에 수전증까지 있어서 창피하기도 해서 사람들을 멀리했거든. 맑은 물에 고기가 안 꼬인다는 말도 떠오를 정도니 인제 와서 후회한들 무슨 소용이 있을까?두어 사람과는 붕어빵도 같이 먹고 이런저런 이야기를 나눴으니 비교적 허물없이 지낸 편이지. 지금도 그러면 덜 외롭겠지만 내가 이런저런 이유로 연락을 끊어놓고는 인제 와서 뒤늦게 불쑥 나타나기도 그렇잖아?  당황       281
40885                            미래라는 단어를 들으면 사람들은 장밋빛이나 푸른색을 떠올린다지만 난 우중충한 잿빛이나 검은색이 떠오르니 왜일까? 나이 탓일까 아니면 노후준비가 안 돼 있는 탓일까?예전에 고독사하신 분을 한번 본 적이 있어서 오래전부터 난 우물쭈물하지 말고 미리미리 준비해야지 마음먹었거든? 그런데 살다 보니 이리저리 뜯기는 통에 돈이 어디 뜻대로 손안에 남아줘야지.장례식을 생각만 해도 슬픈데 돈 한 푼도 없이 병만 얻은 내 처지를 떠올리면 더 슬퍼져. 노후준비를 마치지 못한 사람들은 저승사자가 안 데려가면 좋겠어.  슬픔       280
32968                             도대체 왜 내 업무도 아닌 것을 시키는지 모르겠어. 지금 내 업무 만으로도 스트레스 받고 힘이 드는데 분명히 이것은 행정실 쪽의 업무인데도 나에게 하라고 하니 너무 힘들어.뭐 어떻게 할 수 있겠어. 나이 들어서 업무 가지고 툴툴거리는 것도 너무 보기에 우습잖아. 그냥 혼자 삭히고 하는 수밖에 없지. 어휴 정말 너무 짜증이 나.어쩔 수 없지 않겠어? 업무에 대해서 하나하나 따지면 내가 얼마나 쪼잔한 사람 같아 보이겠어? 그렇다고 넙죽하기도 싫고 뒤에서 욕하는 수밖에 없어. 내 신세가 참 기막히네.  상처       279
38500                                 나 스무 살에 작은 식품회사에 취직해서 퇴직할 때까지 삼십 년을 다녔어. 나는 이 회사에 들어가서 닥치는대로 열심히 일했어. 식품 만들어내면 포장하는 일을 맡아서 했지.그런데 일을 하면서 자주 내가 하는 일이 누가 알아 주지도 않고 승진할 기회도 별로 없어서 하기 싫다는 생각도 많이 했다가도 집안의 어려운 형편을 생각하고 마음 고친 적 많지.내가 처녀일 때는 먹고 살기에만 신경 써가며 일하러 다니느라고 꿈을 가질 생각을 전혀 못 했는데 내 나이가 많은 지금이라도 새로운 인생을 살고 싶어.  슬픔       275
39590                                 올해 초까지 동네에서 삼십오 년간 전자수리점을 했지. 사양직업이지만 단골이 많아 꽤 재미가 있었어. 그런데 이제 가게를 그만두고 쉬고 있어. 슬픈 일이지.당뇨는 오래전부터 있었는데 당뇨망막증이라나 그것은 갑자기 온다네. 그것 때문에 한쪽 시력은 거의 잃어버렸어. 한쪽은 약하게 보이고. 회로를 못 보니 일을 할 수가 있나.주위에 아파트가 들어서도 우리 가게는 그대로였지. 그 많은 단골을 이제 보지 못한다니 나의 기쁨은 영 사라져버렸어. 기계에 새 삶을 불어 넣는 의사였는데 나는 이게 뭐냐.  슬픔       275
38485                                  내 나이가 벌써 육십육 살이야. 나하고 삼십 년을 함께 살았던 영감은 십 년 전에 먼저 먼 곳으로 영원히 떠나서 나 혼자 되었지. 그런데 지난달에는 내가 사랑하는 사촌오빠가 돌아가셨어.나 자식들하고 같이 안 살고 혼자 나와서 살고 있어. 두 며느리하고 사위한테 부담 주기 싫어서 그렇게 했어. 그러니 외로운 감정 내가 다 감당해야지.내가 어릴 때 사고로 머리 다치면서 오랫동안 치료받았어. 결혼하고서도 치료받고 있었어. 사랑하는 사람들을 먼저 떠나보내면서 머리가 더 아파서 힘들 때가 많지.  슬픔       274
33371                                     친구들 모두 행복하게 연애 중인데 나는 연애를 하고 싶어도 좋은 인연을 만나지 못하고 있어. 같이 모임을 해도 모두 애인과 함께 오고 나만 혼자니까 열등감이 들어서 피하게 돼.내가 혼자인 것을 외로워서 못 견뎌 하는 것이 가장 큰 문제인 것 같아. 혼자서도 즐거운 일들이 많다는 걸 깨달아 가는 것이 중요할 것 같아.혼자 할 수 있는 즐거운 일이 무얼까 생각하다가 카페 탐방을 생각했어. 평소 디저트류를 좋아하니까 예쁘고 특이한 디저트가 많은 카페를 탐방하며 소소한 행복을 찾을 거야.  당황       271
39569                                     살다 보니 좋은 날도 있고 그렇지 않은 날도 있다지만 생각으로는 노년이 되면 부부가 모두 건강하게 살다가 가는 게 제일이라는 것을 이제야 알게 되었어.흔히들 백년해로하자고 하는데 부부중 어느 한쪽이든 양쪽이든 건강이 나쁘거나 혹은 일찍 사별 하면 이런 백년해로를 못 하게 되니 얼마나 많은 좋은 업을 쌓아야 할까?그런데 그런 어려운 사항이 지금 내가 안고 있으니 아내가 병석에 누워 있는데 내 몸도 부실 하여 환자 돌보는 것이 좀 힘에 부치지 물론 경제적 어려움도 따르니 죽을 맛이지.  당황       271

In [30]:
# 142 초과 텍스트 비율
over_142 = final_df[final_df["text_len"] > 142]
print(f"142 초과: {len(over_142)}건 ({len(over_142)/len(final_df)*100:.1f}%)")
print(over_142[["사람문장", "감정", "text_len"]].sort_values("text_len", ascending=False).head(20).to_string())

142 초과: 2827건 (4.9%)
                                                                                                                                                                                                                                                                                                                     사람문장  감정  text_len
38631  아 산다는 것이 무엇인지 조금은 알겠는데 그래도 힘이 드네. 그럭저럭 먹고살 만하게 경제적으로 힘든 것은 없는데 자식 농사를 잘 마감 해야하 는데 소통이 잘 안 되니 말이야.옛말에 부자 삼 대 못 간 다는 말이 있듯이 우리와 나의 부친은 굶으면서 자식들 안 굶기도 학교 마치라고 부유하지는 안 해도 온 정성을 다했는데 얘들은 이걸 모르니.해서 애들을 조금 힘들게 키워야 하는데 외국 유학까지 보내서 공부하도록 했더니 허황된 다른 견들만 갖고서 생활하려 하니 내가 틀리는지 자식들 의견이 다른지 고민이네. 퇴직을 앞두고 이런 고민을 하는 게 불행해.  상처       306
40854  가방끈이 짧다는 말이 무슨 뜻인 줄 알지? 학력이 낮다는 말인데 내가 그래서 친구들은 물론 가족들에게도 무시를 받는 것 같아. 텔레비전에서 나오는 말을 못 알아들을 때도 그렇고 거리에서 간판을 못 읽을 때도 그렇고 수없이 많아. 가족들이 나누는 얘기를 못 알아들을 때 가족들이 나를 바라보는 눈초리는 무시를 넘어서 학대를 하는 느낌이더라고. 게을러서 도중에 포기한 탓에 가방끈이 더 짧아졌지만 주변 사람들하고도 영 안 통하고 외톨이로 지낸다니까. 학교를 그만둔 뒤로 혼자서 한글은 뗐는데 이왕이면 알파벳도 익힐 걸 그랬다는 생각이 뒤늦게 들더라고.  당황       306
40884  남들처럼 배우질 못해서 몸만 믿고 살아왔는데 다리를 다쳤으니 어떡한담. 종일 쉬엄쉬엄 걸어 다녔는데 그걸 못하면 풀칠하기도 힘들 텐데.건강기능식품 같은 걸 파는 외판원을 하고 있는데 나이에 구애도 받지 않고 부지런만 하면 굶어 죽지는 않거든. 얼마 전에는 단골들이랑 산에 올랐다가 미끄러져서 병원을 찾았더니 의사가 앞으로는 한 시간 이상 걷지도 말라잖아.하루 벌어 하루 풀칠하는 형편이니 차가 있을 리도 없지만 차를 누가 주더라도 운전할 줄이나 알겠어? 다리뿐 아니라 귀도 나쁘고 눈도 나쁘고 나쁜 데가 한두 군데가 아니니 죽는 게 나을지도 모르지  분노       306
40889         아무리 바쁜 세상이라고들 하지만 자식들이 돼서 이렇게 무심할 수가 있는 거야? 요즘은 키우는 개도 혼자 오래 내버려 두면 걸린다는데 부모를 방치하는 건 죄가 안 되나 보지?몸이 아픈 어미가 오늘 저녁에 풍이나 치매에 걸릴 줄도 모르는 판인데 더 급한 일이 있겠어? 나이 먹어 보라지 멀쩡한 데가 어디 한 군데라도 남아 있나.이름은 모르겠는데 암튼 척추질환이 있는 데다 산에 나물 뜯으러 갔다가 넘어져서 발까지 삔 뒤론 꼼짝도 못 하겠어. 아파서 아무것도 못 하고 누워 있으려니 자식들한테 더 무시 받는 것 같아 힘들고 두려워서 죽겠어.  당황       299
38503         요즘 들어 외롭다는 생각이 자주 들어. 세상이 변한 건지 내가 변한건지 주변에 있던 말 친구 조차하나둘 떠나 버리고 이 넓은 세상에 나만 혼자 남겨졌다는 생각이 들 때가 있어.말이 통하는 사람이 주변에 없다 보니 나 혼자서 보내는 시간이 많아지고 소외되었다는 생각에 외로움이 더욱 커지는 것을 실감해. 어쩌다 새롭게 알게 된 사람이 생겨도 믿을 수가 없고.그렇긴 하지만 하도 어수선한 세상이라서 좋은 사람인지 나쁜 사람인지 도통 알 수가 없으니 사귀는 게 불안한 건 사실이야. 내가 배운 게 짧아서 대화를 나누기가 자신이 없기도 하고.  상처       299
32298             어제 우리 아들이 무슨 잘못을 해서 야단을 좀 쳤는데 글쎄 걔 말이 엄마가 자기한테 해 준 게 뭐가 있냐고 하는데 기가 막히네. 내가 애들 뒷바라지를 하느라 얼마나 고생을 했는데.아들이 그림을 좀 잘 그리는 편이긴 한데 내가 미대는 절대 안 된다고 하고 그림 도구 같은 걸 다 버렸거든. 근데 부모가 돼서 자식 진로에 대한 결정은 할 수 있지 않겠어?애가 공부할 시간도 없는데 틈만 나면 붓을 잡고 있으니 나도 화가 나서 그랬지. 아들한테 좀 미안한 마음은 있긴 한데 그렇다고 부모한테 그렇게 말을 하는 게 더 나쁜 거 아닌가?  분노       295
40881              변변한 취미도 없고 아픈 데도 많아서 집 근처를 어슬렁거리는 게 유일한 낙인데 그것도 못 하게 됐네. 이러다간 한 걸음도 못 떼어놓는 신세가 될까 봐 걱정이 이만저만이 아니야.집 근처를 왔다 갔다 하는 거야 뭐 마스크를 쓰면 되지만 퇴행성관절염이 심해진 건 수가 없으니. 부모님께 물려받은 위장병에는 걷는 것도 도움이 되고 나도 걷는 걸 좋아하는데. 없는 살림에 해볼 건 다 해본 후 요즘에는 건강기능식품을 열심히 먹고 있어. 다리가 괜찮을 때는 전철로 먼 데까지 가서 국밥도 먹고 왔는데 요즘에는 화장실 가는 것조차 힘들어.  상처       294
38606               내 나이가 예순일곱이야. 내가 이 나이 되면 다른 집에선 부양을 받을 나이인데 나는 지금도 가족 중에서 우리 영감을 부양해야 해서 식당에 일하러 다니고 있어. 외동딸은 외국에서 살지.그래. 나 영감이 중병에 걸려서 간호해야 하고 병원에도 데리고 갔다 와야 하고 일도 하러 다녀야 해. 나도 사실은 신경이 예민해서 쓰러진 적도 있어서 정신과 약을 먹고 있어.우리 집 형편이 이렇게 어려워서 나도 일하러 다녀야 하고 몸이 아픈 영감을 간호해야 하고 나까지도 정신과 치료를 받는 중이어서 나는 무가치한 사람이라는 생각 많이 했어.  분노       293
40877                나이 드니 건강도 나빠지고 수입도 줄어서 사람들을 멀리했더니 모든 게 더 나빠졌네. 몸은 더 약해지고 수입이랑 사람은 끊어졌으니 이걸 어째야 쓸꼬?그게 쉽지 않은 게 사람들을 만나려면 밥값이니 차비니 해서 돈이 만만찮게 들거든. 돈이 없다고 얻어먹으면 오히려 아니 만나느니만 못해서 안 만났더니 사람들을 만나도 화젯거리도 없네. 그런 셈인 게 지금 와서 생각해보니 그나마 주변 사람들 덕에 일거리도 얻고 싱겁게 웃기라도 했는데. 지금은 돈이 한 푼도 없으니 언제 어디서 돈 들어갈 일이 터질까 하고 주위를 두리번거린다니까.  불안       292
38834                    나 처녀 때 직장에 취업해서 열심히 일하고 다녔어. 내 바로 위에 오빠가 있는데 대학에 들어가서 공부를 해서 집안에서 딸인 나는 오빠 대신에 가장 역할을 해야 해서 취직했었어.그때는 오빠만 잘 되면 모든 것이 잘 되고 나도 잘될 거라고 생각해서 그렇게 살아왔어. 그러다 나도 시집가서 자식을 낳아 기르게 되어 직장을 그만두게 되었어.내가 자식을 열심히 기르면 잘 자라서 자식들이 나를 알아줄 줄 알았는데 그렇지가 않아. 나하고 다 따로 살아서 나는 용돈 조금 겨우 받고 지내느라고 내가 하고 싶은 거 할 수가 없어.  불안       288
33380                       친구가 가방을 골라 달라고 하기에 적극적으로 추천해 줬는데 나중에 보니 다른 친구가 추천한 가방을 샀더라고. 이뿐 아니라 친구들이 내 제안을 계속 무시해서 자꾸만 좌절해.어차피 내 의견이 그리 중요하진 않은 것 같아. 나에게 친구들이 의견을 묻는다면 다른 사람들이 어떻게 말했냐고 물어본 후 나도 그렇게 생각한다고 대충 맞장구치고 말 거야.진지하게 의견을 묻는 일이 있다면 성심성의껏 조언을 할 거야. 하지만 일상에서 지나가듯 물어보고 무시하는 행동에 일일이 상처받고 싶지 않아. 그냥 나도 무심히 답할 거야.  분노       285
27655                         아 결국 친구한테 빌려준 돈을 떼이게 생겼어. 급전이 필요하다고 부탁해서 여러차례 빌려준게 벌써 천 만원이 넘는데 십 년이 지나도 갚을 생각을 안하는것 같아 연락을 했더니 전화번호도 바꾸고 잠적해버렸네. 나뿐만 아니고 이 친구한테 당한 사람이 한둘이 아냐. 아주 상습범이더구만.각별히 친했다기 보다는 오래 알고 지내던 사이였는데 평소에 들리는 소문이 좀 좋진 않았어도 설마설마 했는데 아주 사기꾼이었다고 하더라고. 내일 당장 경찰서에 가서 고소할거야.딸이 왜 그런 선택을 하게 되었는지 대화를 나눠봐야겠어.  상처       283
40888                           사람들이 통 안 보이니 인걸은 간데없다는 옛날에 배운 시조까지 갑자기 떠오르네? 다 내 탓이긴 하지만. 내가 좀 예민한 편인 데다 깔끔하기도 하고 그 위에 수전증까지 있어서 창피하기도 해서 사람들을 멀리했거든. 맑은 물에 고기가 안 꼬인다는 말도 떠오를 정도니 인제 와서 후회한들 무슨 소용이 있을까?두어 사람과는 붕어빵도 같이 먹고 이런저런 이야기를 나눴으니 비교적 허물없이 지낸 편이지. 지금도 그러면 덜 외롭겠지만 내가 이런저런 이유로 연락을 끊어놓고는 인제 와서 뒤늦게 불쑥 나타나기도 그렇잖아?  당황       281
40885                            미래라는 단어를 들으면 사람들은 장밋빛이나 푸른색을 떠올린다지만 난 우중충한 잿빛이나 검은색이 떠오르니 왜일까? 나이 탓일까 아니면 노후준비가 안 돼 있는 탓일까?예전에 고독사하신 분을 한번 본 적이 있어서 오래전부터 난 우물쭈물하지 말고 미리미리 준비해야지 마음먹었거든? 그런데 살다 보니 이리저리 뜯기는 통에 돈이 어디 뜻대로 손안에 남아줘야지.장례식을 생각만 해도 슬픈데 돈 한 푼도 없이 병만 얻은 내 처지를 떠올리면 더 슬퍼져. 노후준비를 마치지 못한 사람들은 저승사자가 안 데려가면 좋겠어.  슬픔       280
32968                             도대체 왜 내 업무도 아닌 것을 시키는지 모르겠어. 지금 내 업무 만으로도 스트레스 받고 힘이 드는데 분명히 이것은 행정실 쪽의 업무인데도 나에게 하라고 하니 너무 힘들어.뭐 어떻게 할 수 있겠어. 나이 들어서 업무 가지고 툴툴거리는 것도 너무 보기에 우습잖아. 그냥 혼자 삭히고 하는 수밖에 없지. 어휴 정말 너무 짜증이 나.어쩔 수 없지 않겠어? 업무에 대해서 하나하나 따지면 내가 얼마나 쪼잔한 사람 같아 보이겠어? 그렇다고 넙죽하기도 싫고 뒤에서 욕하는 수밖에 없어. 내 신세가 참 기막히네.  상처       279
38500                                 나 스무 살에 작은 식품회사에 취직해서 퇴직할 때까지 삼십 년을 다녔어. 나는 이 회사에 들어가서 닥치는대로 열심히 일했어. 식품 만들어내면 포장하는 일을 맡아서 했지.그런데 일을 하면서 자주 내가 하는 일이 누가 알아 주지도 않고 승진할 기회도 별로 없어서 하기 싫다는 생각도 많이 했다가도 집안의 어려운 형편을 생각하고 마음 고친 적 많지.내가 처녀일 때는 먹고 살기에만 신경 써가며 일하러 다니느라고 꿈을 가질 생각을 전혀 못 했는데 내 나이가 많은 지금이라도 새로운 인생을 살고 싶어.  슬픔       275
39590                                 올해 초까지 동네에서 삼십오 년간 전자수리점을 했지. 사양직업이지만 단골이 많아 꽤 재미가 있었어. 그런데 이제 가게를 그만두고 쉬고 있어. 슬픈 일이지.당뇨는 오래전부터 있었는데 당뇨망막증이라나 그것은 갑자기 온다네. 그것 때문에 한쪽 시력은 거의 잃어버렸어. 한쪽은 약하게 보이고. 회로를 못 보니 일을 할 수가 있나.주위에 아파트가 들어서도 우리 가게는 그대로였지. 그 많은 단골을 이제 보지 못한다니 나의 기쁨은 영 사라져버렸어. 기계에 새 삶을 불어 넣는 의사였는데 나는 이게 뭐냐.  슬픔       275
38485                                  내 나이가 벌써 육십육 살이야. 나하고 삼십 년을 함께 살았던 영감은 십 년 전에 먼저 먼 곳으로 영원히 떠나서 나 혼자 되었지. 그런데 지난달에는 내가 사랑하는 사촌오빠가 돌아가셨어.나 자식들하고 같이 안 살고 혼자 나와서 살고 있어. 두 며느리하고 사위한테 부담 주기 싫어서 그렇게 했어. 그러니 외로운 감정 내가 다 감당해야지.내가 어릴 때 사고로 머리 다치면서 오랫동안 치료받았어. 결혼하고서도 치료받고 있었어. 사랑하는 사람들을 먼저 떠나보내면서 머리가 더 아파서 힘들 때가 많지.  슬픔       274
33371                                     친구들 모두 행복하게 연애 중인데 나는 연애를 하고 싶어도 좋은 인연을 만나지 못하고 있어. 같이 모임을 해도 모두 애인과 함께 오고 나만 혼자니까 열등감이 들어서 피하게 돼.내가 혼자인 것을 외로워서 못 견뎌 하는 것이 가장 큰 문제인 것 같아. 혼자서도 즐거운 일들이 많다는 걸 깨달아 가는 것이 중요할 것 같아.혼자 할 수 있는 즐거운 일이 무얼까 생각하다가 카페 탐방을 생각했어. 평소 디저트류를 좋아하니까 예쁘고 특이한 디저트가 많은 카페를 탐방하며 소소한 행복을 찾을 거야.  당황       271
39569                                     살다 보니 좋은 날도 있고 그렇지 않은 날도 있다지만 생각으로는 노년이 되면 부부가 모두 건강하게 살다가 가는 게 제일이라는 것을 이제야 알게 되었어.흔히들 백년해로하자고 하는데 부부중 어느 한쪽이든 양쪽이든 건강이 나쁘거나 혹은 일찍 사별 하면 이런 백년해로를 못 하게 되니 얼마나 많은 좋은 업을 쌓아야 할까?그런데 그런 어려운 사항이 지금 내가 안고 있으니 아내가 병석에 누워 있는데 내 몸도 부실 하여 환자 돌보는 것이 좀 힘에 부치지 물론 경제적 어려움도 따르니 죽을 맛이지.  당황       271

In [31]:
# 142 초과 데이터 버렸을 때 감정별 손실 확인
over_142 = final_df[final_df["text_len"] > 142]

print("[버려지는 데이터 감정 분포]")
print(over_142["감정"].value_counts())

print("\n[전체 대비 감정별 손실 비율]")
for emotion in final_df["감정"].unique():
    total = len(final_df[final_df["감정"] == emotion])
    lost  = len(over_142[over_142["감정"] == emotion])
    print(f"  {emotion}: {lost}/{total} ({lost/total*100:.1f}% 손실)")

[버려지는 데이터 감정 분포]
감정
분노    560
당황    539
상처    508
슬픔    495
불안    490
기쁨    235
Name: count, dtype: int64

[전체 대비 감정별 손실 비율]
  분노: 560/10417 (5.4% 손실)
  기쁨: 235/7339 (3.2% 손실)
  불안: 490/10433 (4.7% 손실)
  당황: 539/9804 (5.5% 손실)
  슬픔: 495/10127 (4.9% 손실)
  상처: 508/10149 (5.0% 손실)

In [32]:
final_df = final_df[final_df["text_len"] <= 152].reset_index(drop=True)

In [33]:
# 감정별 길이 분포
emotion_order = ["불안", "분노", "상처", "슬픔", "당황", "기쁨"]
data_by_emotion = [final_df[final_df["감정"] == e]["text_len"].values for e in emotion_order]
axes[1].boxplot(data_by_emotion, labels=emotion_order)
axes[1].set_title("감정별 텍스트 길이 분포")
axes[1].set_xlabel("감정")
axes[1].set_ylabel("글자 수")
 
plt.tight_layout()
plt.savefig("text_length_analysis.png", dpi=150)
plt.close()
print("시각화 저장: text_length_analysis.png\n")

시각화 저장: text_length_analysis.png

C:\Users\asia\AppData\Local\Temp\ipykernel_6240\1840082698.py:4: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.
  axes[1].boxplot(data_by_emotion, labels=emotion_order)

## 형태소 분석

In [ ]:
# 1. Java(JDK) 설치하기
# https://www.azul.com/downloads/?package=jdk#zulu
# Windows x86 64-bit 버전(각자 컴 사양에 맞게) msi 파일을 다운받아주세요

# 2. msi를 실행시켜서 Java를 설치해주세요
# 설정 따로 변경할 필요 없이 기본 설정으로 설치

# 3. 환경변수 설정하기
# 내 PC (우클릭) > 속성 > 고급 시스템 설정 > 환경 변수 
# 3-1. 시스템 변수(S) > 새로 만들기
# 변수 이름: JAVA_HOME
# 변수 값: C:\Program Files\Zulu\zulu-26

# 3-2. asia에 대한 사용자 변수(U) > Path 선택 > 편집 > 새로 만들기
# %JAVA_HOME%\bin 
# 입력 후 확인 클릭

# 4. 터미널에서 아래 명령어 실행
# 오류 없이 버전 정보가 잘 나온다면 성공
# java -version

# 5. 터미널에서 아래 명령어 입력(오래걸림 주의!)
# pip install jpype1
# ~\anaconda3\python.exe -m pip install konlpy

In [9]:
# 형태소 분석용 사본 생성
final_df_cleaned = final_df.copy()

In [10]:
# ─────────────────────────────────────────
# 2. 텍스트 정제
# ─────────────────────────────────────────

import re
from konlpy.tag import Okt
okt = Okt()


def advanced_clean_text(text: str) -> str:
    """특수문자 제거 및 특허 기반 부정문 처리 규칙 적용"""
    # 한글, 영문, 숫자, 문장부호는 남기고 특수문자 제거
    text = re.sub(r'[^\w\s가-힣.,!?]', ' ', text)
    # 연속 공백 제거
    text = re.sub(r'\s+', ' ', text).strip()
    
    # 형태소 분석 및 정규화 (Okt의 stem/norm 활용으로 오타 교정)
    # ex) "알쥐"->"알지" "슬프지"->"슬프다"
    tokens = okt.pos(text, stem=True, norm=True)
    
    # 특허 로직: 부정 어구(않다, 안, 못 등) 감지 시 앞 단어의 의미 반전
    # ex) "슬프지 않다"에서 "슬픔" 키워드만 추출하면 안됨
    # 슬프지 않은데 슬프다고 인식될 수 있기 때문
    # 뒤에 오는 부정문 "않다"를 감지해서 슬픔 감정을 반전시켜야한다
    negation_words = ['않다', '안', '못', '없다', '아니다']
    processed_tokens = []
    
    for i, (word, pos) in enumerate(tokens):
        if word in negation_words and processed_tokens:
            # 부정어가 오면 바로 앞의 감정 형용사/동사에 'NOT_' 접두사를 붙여 의미 보존
            processed_tokens[-1] = "NOT_" + processed_tokens[-1]
        if pos in ['Noun', 'Verb', 'Adjective']:
            processed_tokens.append(word)
            
    return " ".join(processed_tokens)

print("텍스트 정제 및 부정문 처리 중...")
final_df_cleaned["사람문장"] = final_df_cleaned["사람문장"].apply(advanced_clean_text)
# 텍스트 길이 2자 미만 제거 (합치기 과정에서 생긴 빈 행 처리)
final_df_cleaned = final_df_cleaned[final_df_cleaned["사람문장"].str.len() >= 2].reset_index(drop=True)

텍스트 정제 및 부정문 처리 중...

In [11]:
# 전처리된 결과 확인
print(final_df_cleaned["사람문장"].head())

# 전처리 전 원본 사람문장:
# 일은 왜 해도 해도 끝이 없을까? 화가 난다. 그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.
# 전처리 결과:
# 일 왜 해도 해도 NOT_끝 없다 화가 나다 그냥 내 해결 하다 게 남 부담 주다 ...

0    일 왜 해도 해도 NOT_끝 없다 화가 나다 그냥 내 해결 하다 게 남 부담 주다 ...
1    이번 달 또 급여 깎다 물가 오르다 월급 자꾸 깎다 화가 나 최대한 지출 억제 하다...
2    회사 신입 들어오다 말투 거슬리다 그렇다 애 매일 보다 하다 생각 하다 스트레스 받...
3    직장 막내 이유 나 온갖 심부름 시키다 일도 많다 데 정말 분하다 섭섭하다 직장 사...
4    얼마 전 입사 신입사원 나르다 무시 하다 것 같다 화가 나 상사 나 먼저 인사 NO...
Name: 사람문장, dtype: object

In [ ]:
# # 형태소 분석된 파일 생성
# # 이미 파일 있으면 오류 발생
# final_df_cleaned.to_csv("model1_dataset_cleaned.csv", index=False, encoding="utf-8-sig")
# print(f"\n✅ 저장 완료: model1_dataset2.csv ({len(final_df)}행)")

✅ 저장 완료: model1_dataset2.csv (58269행)

## 클래스별 가중치 적용

In [34]:
# ─────────────────────────────────────────
# 3. 클래스 불균형 확인 및 class_weight 계산
# ─────────────────────────────────────────
print("[클래스 분포]")
label_counts = final_df["label"].value_counts().sort_index()
emotion_names = {0:"불안", 1:"분노", 2:"상처", 3:"슬픔", 4:"당황", 5:"기쁨"}
 
for label, count in label_counts.items():
    pct = count / len(final_df) * 100
    bar = "█" * int(pct / 2)
    print(f"  {label} {emotion_names[label]:3s} | {bar:25s} {count:6d}건 ({pct:.1f}%)")
 
# sklearn으로 class_weight 계산 (학습 시 손실함수에 전달)
classes = np.array(sorted(final_df["label"].unique()))
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=final_df["label"]
)
class_weight_dict = dict(zip(classes.tolist(), weights.tolist()))
 
print("\n[class_weight (학습 시 사용)]")
for label, w in class_weight_dict.items():
    print(f"  {label} {emotion_names[label]:3s}: {w:.4f}")
 
# 이진 분류용 pos_weight (부정 감정 비율)
neg_count = final_df["is_negative"].sum()
pos_count = len(final_df) - neg_count
binary_pos_weight = pos_count / neg_count
print(f"\n[이진 분류 pos_weight]: {binary_pos_weight:.4f}")
print(f"  긍정(기쁨): {pos_count}건 / 부정: {neg_count}건")

[클래스 분포]
  0 불안  | ████████                   10184건 (17.9%)
  1 분노  | ████████                   10166건 (17.9%)
  2 상처  | ████████                    9885건 (17.4%)
  3 슬픔  | ████████                    9901건 (17.4%)
  4 당황  | ████████                    9541건 (16.8%)
  5 기쁨  | ██████                      7222건 (12.7%)

[class_weight (학습 시 사용)]
  0 불안 : 0.9312
  1 분노 : 0.9328
  2 상처 : 0.9593
  3 슬픔 : 0.9578
  4 당황 : 0.9939
  5 기쁨 : 1.3131

[이진 분류 pos_weight]: 0.1454
  긍정(기쁨): 7222건 / 부정: 49677건

## 계층화 분할 (Stratified Split)

In [35]:
# 훈련 : 검증 : 테스트 = 8 : 1 : 1 비율로 분할
# 각 감정 클래스 비율을 유지하면서 분할
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    final_df, test_size=0.2, random_state=42, stratify=final_df['label']
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, random_state=42, stratify=temp_df['label']
)

In [37]:
print(f"\n[Train/Val/Test 분리]")
print(f"  Train : {len(train_df)}행 ({len(train_df)/len(final_df)*100:.1f}%)")
print(f"  Val   : {len(val_df)}행 ({len(val_df)/len(final_df)*100:.1f}%)")
print(f"  Test  : {len(test_df)}행 ({len(test_df)/len(final_df)*100:.1f}%)")
 
# 분리 후 감정 분포가 균등한지 확인
print("\n[분리 후 감정 분포 확인]")
split_check = pd.DataFrame({
    "train": train_df["감정"].value_counts(normalize=True).round(3),
    "val":   val_df["감정"].value_counts(normalize=True).round(3),
    "test":  test_df["감정"].value_counts(normalize=True).round(3),
})
print(split_check)

[Train/Val/Test 분리]
  Train : 45519행 (80.0%)
  Val   : 5690행 (10.0%)
  Test  : 5690행 (10.0%)

[분리 후 감정 분포 확인]
    train    val   test
감정
불안  0.179  0.179  0.179
분노  0.179  0.179  0.179
슬픔  0.174  0.174  0.174
상처  0.174  0.174  0.174
당황  0.168  0.168  0.168
기쁨  0.127  0.127  0.127

In [38]:
# # 결과 저장
# # 이미 파일 있으면 오류 발생
train_df.to_csv("model1_train.csv", index=False, encoding="utf-8-sig")
val_df.to_csv("model1_val.csv", index=False, encoding="utf-8-sig")
test_df.to_csv("model1_test.csv", index=False, encoding="utf-8-sig")

## KLUE-BERT 모델

In [ ]:
# 터미널에서 설치
# pip install datasets

In [43]:
# ─────────────────────────────────────────
# 5. HuggingFace datasets 형식으로 변환
#    → KLUE-BERT 학습 파이프라인에 바로 연결 가능
# ─────────────────────────────────────────
try:
    from datasets import Dataset, DatasetDict
 
    def to_hf_dataset(df):
        return Dataset.from_dict({
            "text":        df["사람문장"].tolist(),
            "label":       df["label"].tolist(),
            "is_negative": df["is_negative"].tolist(),
        })
 
    dataset = DatasetDict({
        "train": to_hf_dataset(train_df),
        "val":   to_hf_dataset(val_df),
        "test":  to_hf_dataset(test_df),
    })
 
    dataset.save_to_disk("model1_hf_dataset")
    print("\n[HuggingFace Dataset 저장 완료]")
    print(dataset)
 
except ImportError:
    print("\n⚠ datasets 라이브러리 없음 → CSV로 대체 저장")
    print("   pip install datasets 후 재실행하면 HuggingFace 형식으로 저장됩니다")
 
# CSV도 함께 저장 (백업 및 EDA용)
train_df.to_csv("model1_train.csv", index=False, encoding="utf-8-sig")
val_df.to_csv("model1_val.csv",   index=False, encoding="utf-8-sig")
test_df.to_csv("model1_test.csv",  index=False, encoding="utf-8-sig")
print("\n[CSV 저장 완료]")
print("  model1_train.csv / model1_val.csv / model1_test.csv")

Saving the dataset (0/1 shards):   0%|          | 0/45519 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5690 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5690 [00:00<?, ? examples/s]

[HuggingFace Dataset 저장 완료]
DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'is_negative'],
        num_rows: 45519
    })
    val: Dataset({
        features: ['text', 'label', 'is_negative'],
        num_rows: 5690
    })
    test: Dataset({
        features: ['text', 'label', 'is_negative'],
        num_rows: 5690
    })
})

[CSV 저장 완료]
  model1_train.csv / model1_val.csv / model1_test.csv

In [44]:
# ─────────────────────────────────────────
# 6. 학습에 바로 쓸 수 있는 설정값 출력
# ─────────────────────────────────────────
print("\n" + "="*50)
print(" 학습 설정값 요약 (복사해서 사용)")
print("="*50)
print(f"""
MAX_LEN      = {recommended_max_len}
NUM_LABELS   = 6
BATCH_SIZE   = 32       # GPU 메모리에 따라 조정
EPOCHS       = 5
LR           = 2e-5     # BERT fine-tuning 권장값
 
CLASS_WEIGHT = {class_weight_dict}
 
# 이진 분류(BCEWithLogitsLoss) 사용 시
POS_WEIGHT   = {binary_pos_weight:.4f}
""")

==================================================
 학습 설정값 요약 (복사해서 사용)
==================================================

MAX_LEN      = 152
NUM_LABELS   = 6
BATCH_SIZE   = 32       # GPU 메모리에 따라 조정
EPOCHS       = 5
LR           = 2e-5     # BERT fine-tuning 권장값

CLASS_WEIGHT = {0: 0.9311829012830584, 1: 0.9328316610925307, 2: 0.9593491822626876, 3: 0.9577988755344577, 4: 0.9939384411137896, 5: 1.313094249053817}

# 이진 분류(BCEWithLogitsLoss) 사용 시
POS_WEIGHT   = 0.1454

## Ko-BERT 모델

### 토큰화

In [ ]:
# 터미널에서 아래 명령어 실행
# conda install pytorch torchvision torchaudio cpuonly -c pytorch
# conda install -c conda-forge transformers
# conda install -c conda-forge regex
# pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'

In [13]:
import regex
print(regex.__version__)

2026.4.4

In [14]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from transformers import BertModel
from kobert_tokenizer import KoBERTTokenizer

# KoBERT 모델 사용
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
bert_model = BertModel.from_pretrained('skt/kobert-base-v1')

ModuleNotFoundError: No module named 'kobert_tokenizer'

In [ ]:
# 3. KoBERT 전용 Dataset 클래스 정의 
class KoBERTDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.max_len = max_len
        # '사람문장' 컬럼의 텍스트와 'label' 컬럼의 감정 값을 리스트로 변환
        self.sentences = dataframe['사람문장'].tolist()
        self.labels = dataframe['label'].tolist()

    def __getitem__(self, i):
        # 텍스트 토큰화 및 인코딩 [1]
        # truncation=True와 padding='max_length'를 통해 길이를 통일합니다.
        encoding = self.tokenizer.encode_plus(
            self.sentences[i],
            add_special_tokens=True, # [CLS], [SEP] 추가 [4]
            max_length=self.max_len,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(self.labels[i], dtype=torch.long)
        }

    def __len__(self):
        return len(self.labels)

In [ ]:
# 4. 데이터 로드 및 적용
train_df = pd.read_csv("model1_train.csv")
val_df = pd.read_csv("model1_val.csv")
test_df = pd.read_csv("model1_test.csv")

# 데이터셋 생성
train_dataset = KoBERTDataset(train_df, tokenizer, max_len)
val_dataset = KoBERTDataset(val_df, tokenizer, max_len)
test_dataset = KoBERTDataset(test_df, tokenizer, max_len)

# 5. DataLoader 생성 [2]
# 훈련 안정화를 위해 셔플(shuffle)을 적용합니다.
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size)

print(f"데이터셋 준비 완료! 배치 개수: {len(train_dataloader)}")

# 챗봇 대화 생성 모델

In [30]:
# 사람문장과 시스템문장 분리하기

# 데이터프레임 섞기 (대화 내용이 이어지기 때문)
shuffled_train = fin_t.sample(frac=1).reset_index(drop=True)
shuffled_test = fin_v.sample(frac=1).reset_index(drop=True)


shuffled_train.head()

# train 데이터
rows = []

# 각 행에 대해 사람문장과 시스템문장을 분리
for idx, row in shuffled_train.iterrows():
    # 사람문장1에 대한 시스템문장1
    if pd.notna(row['사람문장1']) and pd.notna(row['시스템문장1']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장1'],
            '시스템문장': row['시스템문장1']
        })
    
    # 사람문장2에 대한 시스템문장2
    if pd.notna(row['사람문장2']) and pd.notna(row['시스템문장2']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장2'],
            '시스템문장': row['시스템문장2']
        })

    # 사람문장3에 대한 시스템문장3 (NaN이 아닌 경우에만 추가)
    if pd.notna(row['사람문장3']) and pd.notna(row['시스템문장3']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장3'],
            '시스템문장': row['시스템문장3']
        })

# 새로운 데이터 프레임 생성
train = pd.DataFrame(rows)

train.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장,시스템문장
0,청년,여성,대인관계,해당없음,당황,당황,친구가 가지고 싶어 하던 물건을 선물해 주었는데 다른 친구한테 방금 똑같은 걸 받았...,친구가 선물을 주려고 했는데 이미 똑같은 선물을 받은 상태라서 많이 당황하셨을 것 ...
1,청년,여성,대인관계,해당없음,당황,당황,내가 꼭 주고 싶었던 선물인데 이미 받았다니 너무 속상해.,정말 속상하시겠어요. 이 상황을 해결할 방법에는 어떤 것이 있을까요?
2,청년,여성,대인관계,해당없음,당황,당황,친구에게 물어봐서 필요하다면 주고 안 필요하다면 내가 가져야겠어.,운동하고 나 자신을 관리해야겠다고 생각하시는군요.
3,청년,여성,"진로,취업,직장",해당없음,불안,불안,입사 후에 업무에 잘 적응할 수 있을지 정말 불안해.,업무 적응 때문에 불안해하시는군요.
4,청년,여성,"진로,취업,직장",해당없음,불안,불안,내가 다른 사람들보다 꼼꼼해서 느리거든. 결과는 잘 만들 수 있는데 느려서 걱정돼.,그런 상황을 변화시키기 위해서 어떻게 하면 될까요?

In [31]:
train['감정_대분류'].value_counts()

감정_대분류
불안    27960
분노    27480
상처    27429
슬픔    27375
당황    26268
기쁨    18378
Name: count, dtype: int64

In [32]:
# test 데이터
rows = []

# 각 행에 대해 사람문장과 시스템문장을 분리
for idx, row in shuffled_test.iterrows():
    # 사람문장1에 대한 시스템문장1
    if pd.notna(row['사람문장1']) and pd.notna(row['시스템문장1']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장1'],
            '시스템문장': row['시스템문장1']
        })
    
    # 사람문장2에 대한 시스템문장2
    if pd.notna(row['사람문장2']) and pd.notna(row['시스템문장2']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장2'],
            '시스템문장': row['시스템문장2']
        })

    # 사람문장3에 대한 시스템문장3 (NaN이 아닌 경우에만 추가)
    if pd.notna(row['사람문장3']) and pd.notna(row['시스템문장3']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장3'],
            '시스템문장': row['시스템문장3']
        })

# 새로운 데이터 프레임 생성
test = pd.DataFrame(rows)

test.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장,시스템문장
0,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,여자친구가 배가 아프다고 해. 그래서 업고 병원을 찾는 중인데 보이질 않아.,여자친구가 아프시다니 정말 초조하겠어요.
1,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,도저히 병원을 못 찾겠는데 어떻게 해야 하지.,병원을 찾고 계시군요. 어떻게 해야 빠르게 찾을 수 있을까요?
2,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,생각해보니 스마트폰으로 병원의 위치를 찾을 수 있어. 빨리 여자친구를 데려가야겠어.,여자친구가 잘 치료받고 아프지 않았으면 좋겠어요.
3,중년,남성,건강,해당없음,당황,부끄러운,시력이 많이 안 좋아져서 검사를 받았는데 스마트폰을 너무 많이 봐서 그렇다고 해. ...,시력 관리를 잘하지 못해 부끄러우시군요. 스마트폰의 사용을 줄이기 위해선 어떤 습관...
4,중년,남성,건강,해당없음,당황,부끄러운,꼭 필요한 순간이 아니면 사용을 안 해야지. 무제한 요금제라서 습관적으로 하게 되는...,데이터를 제한하면 과도한 사용이 줄어들 수도 있겠네요. 스마트폰의 사용을 줄여 눈 ...